apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-infrastructure-as-code
spec:
  template:
    spec:
      containers:
        - name: microservice
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080
