schemaVersion: '2.0.0' # Make sure to test the latest schema version
commandTests:
- name: 'path'
  command: 'sh'
  args: ['-c', 'echo $PATH']
  expectedOutput: ['/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin']
fileContentTests:
- name: 'Index HTML'
  expectedContents: ['Hello, World!']
  path: '/usr/share/nginx/html/index.html'
- name: 'Passwd file'
  expectedContents: ['root:x:0:0:root:/root:/bin/bash']
  path: '/etc/passwd'
fileExistenceTests:
- name: 'Root'
  path: '/'
  shouldExist: true
  uid: 0
  gid: 0
- name: 'Hosts File'
  path: '/etc/hosts'
  shouldExist: true
- name: 'Dummy File'
  path: '/etc/dummy'
  shouldExist: false