apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/runatlantis/atlantis/kustomize

resources:
- secrets.yaml

patchesStrategicMerge:
- github.yaml
# - loadbalancer.yaml
- ingress.yaml
