apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: cloud-infrastructure-as-code

namespace: default
nameSuffix: -v1

resources:
  - microservice-deployment.yaml
  - microservice-service.yaml

configMapGenerator:
  - name: microservice-configmap
    files:
      - common.properties
    literals:
      - DEFAULT_MESSAGE=Hello World.
