apiVersion: v1
kind: Service
metadata:
  name: clean-infrastructure-as-code
  labels:
    type: microservice
    env: local
spec:
  ports:
    - port: 8080
      name: http
  selector:
    type: microservice
